import { lazy, createComponent, type Component } from "solid-js";
import type { JSX } from "@solidjs/web";
import type { RouteDefinition, RouteSectionProps } from "@solidjs/router";
import type { RouteConfig } from "../types/route-definition";
import { RouteValidationError } from "../types/route-definition";
import { RouteValidationProvider } from "../context/route-context";
import { validateData } from "../schema/validator-adapter";
import { normalizeSearchParams } from "../schema/coercion";

/**
 * File route ref with dynamic code splitting.
 */
export interface FileRouteLazyRef {
  src: string;
  import(): Promise<Record<string, unknown>>;
}

/**
 * File route ref with static eager delivery.
 */
export interface FileRouteEagerRef {
  src?: string;
  require(): Record<string, unknown>;
}

/**
 * Manifest entry shape emitted by filesystem-routing.
 */
export interface FileRouteEntry {
  path: string;
  page?: boolean;
  $component?: FileRouteLazyRef | FileRouteEagerRef;
  $$route?: FileRouteEagerRef;
  children?: readonly FileRouteEntry[];
  [key: string]: unknown;
}

/**
 * Intercepts route definitions generated by filesystem-routing, injecting
 * validation providers and schema guards without requiring route paths in files.
 */
export function interceptFileRoutes<const TManifest extends readonly unknown[]>(
  entries: TManifest,
): RouteDefinition[] {
  const componentCache = new Map<string, Component<RouteSectionProps>>();

  const resolveComponent = (ref: FileRouteLazyRef | FileRouteEagerRef): Component<RouteSectionProps> => {
    if ("require" in ref) {
      return ref.require().default as Component<RouteSectionProps>;
    }
    let cached = componentCache.get(ref.src);
    if (!cached) {
      cached = lazy(
        ref.import as () => Promise<{ default: Component<RouteSectionProps> }>,
        undefined,
        ref.src,
      );
      componentCache.set(ref.src, cached);
    }
    return cached;
  };

  const transformEntry = (entry: FileRouteEntry): RouteDefinition => {
    const routeExport = entry.$$route?.require()?.route as
      | { config?: RouteConfig }
      | RouteConfig
      | undefined;
    const config: RouteConfig = (routeExport && "config" in routeExport && routeExport.config
      ? routeExport.config
      : (routeExport as RouteConfig)) ?? {};

    let component: Component<RouteSectionProps> | undefined = undefined;
    if (entry.$component) {
      const RawComp = resolveComponent(entry.$component);
      component = (props: RouteSectionProps): JSX.Element => {
        return createComponent(RouteValidationProvider, {
          config,
          get children() {
            return createComponent(RawComp, props);
          },
        });
      };
      if ("preload" in RawComp && typeof (RawComp as { preload?: unknown }).preload === "function") {
        const rawPreload = (RawComp as { preload: () => unknown }).preload;
        (component as unknown as { preload: () => unknown }).preload = () => rawPreload();
      }
    }

    let preload = config.preload;
    if (preload && typeof preload === "function") {
      const origPreload = preload;
      preload = (args: Record<string, unknown>): unknown => {
        const rawParams = (args.params as Record<string, string | undefined>) ?? {};
        const locationObj = (args.location as { query?: Record<string, string | string[] | undefined> }) ?? {};
        const rawSearch = normalizeSearchParams(locationObj.query ?? {});

        const paramsRes = validateData(config.params, rawParams);
        if (!paramsRes.success && config.onError) {
          config.onError({
            error: new RouteValidationError("params", paramsRes.issues ?? []),
            rawParams,
            rawSearch,
          });
        }

        const searchRes = validateData(config.search, rawSearch);
        if (!searchRes.success && config.onError) {
          config.onError({
            error: new RouteValidationError("search", searchRes.issues ?? []),
            rawParams,
            rawSearch,
          });
        }

        return origPreload({
          params: paramsRes.data,
          search: searchRes.data,
          location: args.location,
        } as never);
      };
    }

    return {
      ...config,
      path: entry.path,
      component,
      preload: preload as RouteDefinition["preload"],
      info: { ...config.info, filesystem: true },
      children: entry.children ? (entry.children as FileRouteEntry[]).map(transformEntry) : undefined,
    } as RouteDefinition;
  };

  return (entries as unknown as FileRouteEntry[]).map(transformEntry);
}
