// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/(main)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(main)")>;
      $$route?: undefined;
    },
    {
      path: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route?: undefined;
    },
    {
      path: "/(main)/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(main)/index")>;
      $$route?: undefined;
    },
    {
      path: "/api/*slug";
      page: false;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/[...slug]")>;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/[...slug]")>;
      $POST: FileRouteLazyRef<typeof import("./src/routes/api/[...slug]")>;
      $PUT: FileRouteLazyRef<typeof import("./src/routes/api/[...slug]")>;
      $DELETE: FileRouteLazyRef<typeof import("./src/routes/api/[...slug]")>;
      $PATCH: FileRouteLazyRef<typeof import("./src/routes/api/[...slug]")>;
      $OPTIONS: FileRouteLazyRef<typeof import("./src/routes/api/[...slug]")>;
      $QUERY: FileRouteLazyRef<typeof import("./src/routes/api/[...slug]")>;
      $$route?: undefined;
    },
    {
      path: "/(main)/user/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(main)/user/[id]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(main)/user/[id]")>;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/*404";
      id: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/";
      id: "/(main)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(main)")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(main)/index")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/user/:id";
          id: "/user/:id";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(main)/user/[id]")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(main)/user/[id]")>;
          children?: undefined;
        }
      ];
    }
  ];
}
